name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo ps -ef | grep java | grep -v grep | awk '{print $2}' | xargs kill -9
            sudo rm -rf mock-server/
            git clone https://github.com/Dont12/mock-server.git
            cd mock-server/
            echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
            sudo cp ../keystore.p12 ./src/main/resources
            sudo ./gradlew build
            sudo nohup ./gradlew bootRun > nohup.out 2> nohup.err < /dev/null &
